---
apiVersion: v1

kind: Pod

metadata:
  name: liveness-pod

spec:
  containers:
    - name: libeness
      image: nginx:1.22.0

      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 5