apiVersion: apps/v1

kind: Deployment

metadata:
  name: db-deploy
spec:
  selector:
    matchLabels:
      app: postgresdb

  replicas: 1

  template:
    metadata:
      labels:
        app: postgresdb

    spec:
      containers:
        - name: postgresdb
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-secret-credentials

          # envFrom:
          #   - secretRef:
          #       name: pg-secrets
          volumeMounts:
            # The volume mounts  for the container
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            # reference the PersistentVolumeClaim
            claimName: db-persistent-volume-claim
