apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: front-pvc

spec:
  storageClassName: manual

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi
