apiVersion: v1

kind: Pod

metadata:
  name: nginx

spec:
  containers:
  - name: nginx
    image: nginx:1.16.0

    volumeMounts:
    - name: nginx-storage
      mountPath: /data/emptydir

  volumes:
  - name: nginx-storage
    emptyDir: {}
