apiVersion: v1

kind: Secret

metadata:
  name: database-secrets

data:
  MYSQL_ROOT_PASSWORD: d29yZHByZXNz #wordpress
  MYSQL_DATABASE: d29yZHByZXNz #wordpress
  MYSQL_USER: d29yZHByZXNz #wordpress
  MYSQL_PASSWORD: d29yZHByZXNz #wordpress